enum EScreenResize {
  SCREEN_RESIZE = 'SCREEN_RESIZE',
}

enum EAuth {
  AUTH_REQUESTING = 'AUTH_REQUESTING',
  AUTH_DONE = 'AUTH_DONE',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
}

enum EProduct {
  PRODUCT_FETCH_REQUESTING = 'PRODUCT_FETCH_REQUESTING',
  PRODUCT_DONE = 'PRODUCT_DONE',
  PRODUCT_REJECT_FETCH_DONE = 'PRODUCT_REJECT_FETCH_DONE',
  PRODUCT_REJECT_FETCH_SUCCESS = 'PRODUCT_REJECT_FETCH_SUCCESS',
  PRODUCT_SUCCESS = 'PRODUCT_SUCCESS',
  PRODUCT_FAILED = 'PRODUCT_FAILED',
  PRODUCT_CREATE_REQUESTING = 'PRODUCT_CREATE_REQUESTING',
  PRODUCT_CREATE_DONE = 'PRODUCT_CREATE_DONE',
  PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED',
  PRODUCT_UPDATE_REQUESTING = 'PRODUCT_UPDATE_REQUESTING',
  PRODUCT_UPDATE_DONE = 'PRODUCT_UPDATE_DONE',
  PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED',
  PRODUCT_DELETE_REQUESTING = 'PRODUCT_DELETE_REQUESTING',
  PRODUCT_DELETE_DONE = 'PRODUCT_DELETE_DONE',
  PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED',
  PRODUCT_FETCH_SINGLE_REQUESTING = 'PRODUCT_FETCH_SINGLE_REQUESTING',
  PRODUCT_FETCH_SINGLE_DONE = 'PRODUCT_FETCH_SINGLE_DONE',
  PRODUCT_FETCH_SINGLE_SUCCESS = 'PRODUCT_FETCH_SINGLE_SUCCESS',
  PRODUCT_FETCH_SINGLE_FAILED = 'PRODUCT_FETCH_SINGLE_FAILED',
}

enum ECategory {
  FETCH_CATEGORY = 'FETCH_CATEGORY',
  FETCH_CATEGORY_DONE = 'FETCH_CATEGORY_DONE',
}

enum EOrder {
  CREATE_ORDER_REQUESTING = 'CREATE_ORDER_REQUESTING',
  CREATE_ORDER_DONE = 'CREATE_ORDER_DONE',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED',
  DELETE_ORDER_REQUESTING = 'DELETE_ORDER_REQUESTING',
  DELETE_ORDER_DONE = 'DELETE_ORDER_DONE',
  DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS',
  DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED',
  FETCH_ORDER_REQUESTING = 'FETCH_ORDER_REQUESTING',
  FETCH_ORDER_DONE = 'FETCH_ORDER_DONE',
  FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS',
  FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED',
  FETCH_SINGLE_ORDER_REQUESTING = 'FETCH_SINGLE_ORDER_REQUESTING',
  FETCH_SINGLE_ORDER_DONE = 'FETCH_SINGLE_ORDER_DONE',
  FETCH_SINGLE_ORDER_SUCCESS = 'FETCH_SINGLE_ORDER_SUCCESS',
  FETCH_SINGLE_ORDER_FAILED = 'FETCH_SINGLE_ORDER_FAILED',
}

const ActionTypes: {
  [key: string]: any;
} = {
  ...EScreenResize,
  ...EAuth,
  ...EProduct,
  ...EOrder,
  ...ECategory,
};

export { ActionTypes };
