enum EScreenResize {
  SCREEN_RESIZE = 'SCREEN_RESIZE',
}

enum EAuth {
  AUTH_REQUESTING = 'AUTH_REQUESTING',
  AUTH_DONE = 'AUTH_DONE',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
}

enum EProduct {
  PRODUCT_FETCH_REQUESTING = 'PRODUCT_FETCH_REQUESTING',
  PRODUCT_DONE = 'PRODUCT_DONE',
  PRODUCT_SUCCESS = 'PRODUCT_SUCCESS',
  PRODUCT_FAILED = 'PRODUCT_FAILED',
  PRODUCT_CREATE_REQUESTING = 'PRODUCT_CREATE_REQUESTING',
  PRODUCT_CREATE_DONE = 'PRODUCT_CREATE_DONE',
  PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED',
  PRODUCT_UPDATE_REQUESTING = 'PRODUCT_UPDATE_REQUESTING',
  PRODUCT_UPDATE_DONE = 'PRODUCT_UPDATE_DONE',
  PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED',
  PRODUCT_DELETE_REQUESTING = 'PRODUCT_DELETE_REQUESTING',
  PRODUCT_DELETE_DONE = 'PRODUCT_DELETE_DONE',
  PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED',
  PRODUCT_FETCH_SINGLE_REQUESTING = 'PRODUCT_FETCH_SINGLE_REQUESTING',
  PRODUCT_FETCH_SINGLE_DONE = 'PRODUCT_FETCH_SINGLE_DONE',
  PRODUCT_FETCH_SINGLE_SUCCESS = 'PRODUCT_FETCH_SINGLE_SUCCESS',
  PRODUCT_FETCH_SINGLE_FAILED = 'PRODUCT_FETCH_SINGLE_FAILED',
}

const ActionTypes: {
  [key: string]: any;
} = {
  ...EScreenResize,
  ...EAuth,
  ...EProduct,
};

export { ActionTypes };
